// <auto-generated />
using Ceviri.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ceviri.Migrations
{
    [DbContext(typeof(CeviriContext))]
    [Migration("20210408000611_InitilCreate")]
    partial class InitilCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Ceviri.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .HasColumnType("TEXT");

                    b.HasKey("BookId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Ceviri.Models.Supporter", b =>
                {
                    b.Property<int>("SupporterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstMidName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("SupporterId");

                    b.ToTable("Supporters");
                });

            modelBuilder.Entity("Ceviri.Models.Translate", b =>
                {
                    b.Property<int>("TranslateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TranslatorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TranslateId");

                    b.HasIndex("BookId");

                    b.HasIndex("TranslatorId");

                    b.ToTable("Translates");
                });

            modelBuilder.Entity("Ceviri.Models.Translator", b =>
                {
                    b.Property<int>("TranslatorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstMidName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("TranslatorID");

                    b.ToTable("Translators");
                });

            modelBuilder.Entity("Ceviri.Support", b =>
                {
                    b.Property<int>("SupportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Bounty")
                        .HasColumnType("TEXT");

                    b.Property<int>("SupporterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TranslateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SupportId");

                    b.HasIndex("SupporterId");

                    b.HasIndex("TranslateId");

                    b.ToTable("Supports");
                });

            modelBuilder.Entity("Ceviri.Models.Translate", b =>
                {
                    b.HasOne("Ceviri.Models.Book", "Book")
                        .WithMany("Translates")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ceviri.Models.Translator", "Translator")
                        .WithMany("Translates")
                        .HasForeignKey("TranslatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Translator");
                });

            modelBuilder.Entity("Ceviri.Support", b =>
                {
                    b.HasOne("Ceviri.Models.Supporter", "Supporter")
                        .WithMany("Supports")
                        .HasForeignKey("SupporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ceviri.Models.Translate", "Translate")
                        .WithMany("Supports")
                        .HasForeignKey("TranslateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supporter");

                    b.Navigation("Translate");
                });

            modelBuilder.Entity("Ceviri.Models.Book", b =>
                {
                    b.Navigation("Translates");
                });

            modelBuilder.Entity("Ceviri.Models.Supporter", b =>
                {
                    b.Navigation("Supports");
                });

            modelBuilder.Entity("Ceviri.Models.Translate", b =>
                {
                    b.Navigation("Supports");
                });

            modelBuilder.Entity("Ceviri.Models.Translator", b =>
                {
                    b.Navigation("Translates");
                });
#pragma warning restore 612, 618
        }
    }
}
